name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2'

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build project
      run: msbuild /p:Configuration=Release

    - name: Get Version from AssemblyInfo.cs
      id: version
      run: |
        $version = [System.IO.File]::ReadAllText('ClassLibrary1/Properties/AssemblyInfo.cs') -match 'AssemblyFileVersion\("(.*)"\)'
        Write-Output "::set-output name=version::${matches[1]}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release v${{ steps.version.outputs.version }}
        body: |
          Release notes for v${{ steps.version.outputs.version }}
          - Feature 1
          - Feature 2

    - name: Upload Release Asset
      id: upload_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path/to/your-asset.zip
        asset_name: your-asset.zip
        asset_content_type: application/zip
