name: Build and Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2' # 使用你需要的 .NET 版本

    - name: Restore NuGet packages
      run: dotnet restore ClassLibrary1/SoumaDownloader.csproj

    - name: Build DLL
      run: dotnet build --configuration Release ClassLibrary1/SoumaDownloader.csproj

    - name: Publish DLL
      run: dotnet publish --configuration Release --output ./publish ClassLibrary1/SoumaDownloader.csproj

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload DLL to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/SoumaDownloader.dll
        asset_name: SoumaDownloader.dll
        asset_content_type: application/octet-stream
